# Generated by Django 2.0.7 on 2018-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Identificador'),
        ),
    ]
