# Generated by Django 2.0.7 on 2018-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20180724_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Identificador'),
        ),
    ]
