# Generated by Django 2.0.7 on 2018-07-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20180724_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
